// (c) Copyright 2022 by Abraxas Informatik AG
// For license information see LICENSE file

using System;
using System.Collections.Generic;

namespace Voting.Basis.Core.Domain;

public abstract class PoliticalBusiness
{
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the domain of influence responsible for this political business.
    /// </summary>
    public Guid DomainOfInfluenceId { get; set; }

    /// <summary>
    /// Gets or sets the contest that this political business is part of.
    /// </summary>
    public Guid ContestId { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this political business is active.
    /// This means that all information has been correctly entered and results can be entered for the political business.
    /// </summary>
    public bool Active { get; set; }

    /// <summary>
    /// Gets or sets the political business number (in german: Geschäftsnummer).
    /// </summary>
    public string PoliticalBusinessNumber { get; set; } = string.Empty;

    public Dictionary<string, string> OfficialDescription { get; set; } = new();

    public Dictionary<string, string> ShortDescription { get; set; } = new();

    public string InternalDescription { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a value indicating whether ballot bundle numbers are automatically generated by the system or if users enter the number manually.
    /// </summary>
    public bool AutomaticBallotBundleNumberGeneration { get; set; }
}
